#Run the program by entering make test<number> p=<pattern> 

test1:
	$(MAKE) -C tests p=$(p) test1

test2:
	$(MAKE) -C tests p=$(p) test2

test3:
	$(MAKE) -C tests p=$(p) test3

clean:
	$(MAKE) -C tests clean
